@startuml

left to right direction

class Club{
    -String name
}

class Team{
    -Club: club
    -String name
}

class Member{
    -String firstname
    -String lastname
    -Team team
}

Club"1"-->"*"Team
Team"1"-->"*"Member
Member --|> Coach
Member --|> Player

@enduml
